### ISSUE TITLE
Only works for Pro version

### ISSUE THREAD

**Issue by Missilefool** [alex-smtv/X52-PRO-Mouse-Ministick-to-Axes#2]
Could you edit the code to make one for regular X52. The registry folder is different so if its possible just to replace the digits, everything else should work the same.

The following is the folder location.

HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_06A3&PID_075C

It should be VID_06A3&PID_075C instead of VID_06A3&PID_0762. note that your code has     0762

Please make one where its      075C    instead of     0762

**Comment by alex-smtv** [comment]
Hello @Missilefool ,

You can now look at the [new release](https://github.com/alex-smtv/X52-PRO-Mouse-Ministick-to-Axes/releases/tag/v1.1). I've included a solution for the non-pro X52 with the changes you suggested.

Thank you for your feedback.
